name: Main Build and Preview
run-name: Building Main and Deploying Preview
on:
  push:
    branches:
      - main
jobs:
  Main-Build-and-Preview:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: "453.0.0"
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: "projects/525978447980/locations/global/workloadIdentityPools/my-pool/providers/my-provider-x"
          service_account: "my-service-account@alert-parsec-404117.iam.gserviceaccount.com"
          token_format: "access_token"
          access_token_lifetime: 300s
      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: "Deploy Preview"
        run: |
          gcloud run deploy nextjs-deploy-experiment \
            --region=us-central1 \
            --image=us-central1-docker.pkg.dev/alert-parsec-404117/nextjs-deploy-experiment/nextjs-deploy-experiment:f2150dd \
            --revision-suffix=f2150dd \
            --tag=f2150dd \
            --min-instances=0 \
            --max-instances=5 \
            --port=8080 \
            --no-traffic

      # - name: Set outputs
      #   id: vars
      #   run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      # - name: Check outputs
      #   run: echo ${{ steps.vars.outputs.sha_short }}
      # - id: docker-push-tagged
      #   name: Tag Docker image and push to Google Artifact Registry
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     context: .
      #     file: ./apps/nextjs-deploy-experiment/Dockerfile
      #     platforms: linux/amd64
      #     tags: |
      #       us-central1-docker.pkg.dev/alert-parsec-404117/nextjs-deploy-experiment/nextjs-deploy-experiment:${{ steps.vars.outputs.sha_short }}
      #       us-central1-docker.pkg.dev/alert-parsec-404117/nextjs-deploy-experiment/nextjs-deploy-experiment:latest
